[application]

# dioxus project name
name = "yousofmersal_client"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Yousof Mersal | Computer Science Student"

[web.watcher]

watch_path = [
    "src", 
    "public", 
    "Dioxus.toml",
]

index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = [
    "/assets/tailwind/tailwind.min.js",
    "/assets/tailwind/tailwindcss.config.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[plugin]

available = true

loader = [
# "/home/yousof/MassStorage/Documents/code/rust/yousofmersal.com/services/yousofmersal_client/dioxus-binaryen-plugin"
]

[plugin.dioxus-binaryen]

optimize = true
